[project]
name = "ReminderAI"
version = "0.1.0"
description = "A dummy FastAPI app, for scheduling AI generated WhatsApp reminder massages."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "scheduler>=0.8.8",
    "uvicorn>=0.34.3",
]
